repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
        args:
          - --diff
          - --check-only
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        name: black
        args:
          - --diff
          - --check
